{ name = "purescript-tidy-test"
, dependencies =
  [ "aff"
  , "ansi"
  , "arrays"
  , "console"
  , "control"
  , "dodo-printer"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "lists"
  , "maybe"
  , "debug"
  , "node-buffer"
  , "node-child-process"
  , "node-fs-aff"
  , "node-path"
  , "node-process"
  , "ordered-collections"
  , "partial"
  , "posix-types"
  , "prelude"
  , "purescript-language-cst-parser"
  , "strings"
  , "tuples"
  ]
, packages = ../packages.dhall
, sources = [ "src/**/*.purs", "test/*.purs" ]
}
